### ISSUE TITLE
How to use password command with non-SASL configs

### ISSUE THREAD

**Issue by heywoodlh** [osa1/tiny#406]
I have a Bitlbee instance that I'm just using for myself. I have tried to configure a command to fetch my password to identify with my server but have been unsuccessful doing it.

I have tried using the "command" parameter with the nickserv_ident and pass config options but tiny complains about invalid values in the config file.

Is there a way to use the command parameter with nickserv_ident or pass? If so, could someone provide a snippet? Because I haven't been able to figure it out.

Thanks!

**Comment by osa1** [comment]
I have this in my config:

```yaml
servers:
    - addr: irc.oftc.net
      port: 6697
      tls: true
      nicks: [...]
      nickserv_ident:
        command: 'pass show oftc_nickserv'
```

Does this not work for you? If not could you share your config with the important bits censored?

**Comment by heywoodlh** [comment]
Ah. I am pretty sure I have identified the problem. I am using `tiny` as provided by [nixpkgs](https://github.com/nixos/nixpkgs): https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/irc/tiny/default.nix

Sure enough, when I run `tiny --version`, the version I get is `v0.10.0` (which you released in 2021). I'm guessing my issue is that I'm not on a new enough version of `tiny`, since you [merged external command support at the end of 2022](https://github.com/osa1/tiny/pull/315).


Could you perhaps release a new version and I'll submit a PR to the nixpkgs to update the version?

If not, I could probably build a nix configuration for myself to build `tiny` from source.

**Comment by osa1** [comment]
I just released [v0.11.0][1]. I won't be able to update nixpkgs package myself but it should be straightforward now.

In general I just recommend installing from the git repo with `cargo install --git https://github.com/osa1/tiny`.

[1]: https://github.com/osa1/tiny/releases/tag/v0.11.0

**Comment by heywoodlh** [comment]
Thanks for the quick response! I'll close my issue and revisit if updating to the latest release doesn't resolve it.
